### ISSUE TITLE
Not able to run InDexDa - "FileNotFoundError" 

### ISSUE THREAD

**Issue by peterpeterparker** [eth-library-lab/inDexDa#4]
Hi Parker,

Installation was ok, I was able to follow the documentation and checkout/install the project locally, all good 👍

On the other side, when I try to run the project, with or without tweaking the `args.json`, I face the following error when I run the command `python3 run.py --first_time --scrape --train`:

> Traceback (most recent call last):
>   File "run.py", line 48, in <module>
>     preprocess.processForTrainingBert()
>   File "/Users/daviddalbusco/projects/lab/datadex/NLP/utils/preprocess.py", line 209, in > processForTrainingBert
>     self.makeDirs()
>   File "/Users/daviddalbusco/projects/lab/datadex/NLP/utils/preprocess.py", line 127, in makeDirs
>     os.mkdir(os.path.join(self.current_dir, '../../data/bert_datatrain/0'))
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/daviddalbusco/projects/lab/datadex/NLP/utils/../../data/bert_datatrain/0'

Not rush, definitely something we could try out to solve, if needed, together in January next time we met.

Have a good one
David

**Comment by ParkerEwen5441** [comment]
Resolved. Need to add the tag --first_time when running and it will create the directory and files for you
